spring:
  application:
    name: HelloSecurity
  security:
    user:
      password: test
  h2:
    console:
      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testrestapis
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html